### ISSUE TITLE
7th March work

### ISSUE THREAD

**Issue by mpdmanash** [kunal-iitkgp/BioInformatics#1]
MecA ka sequence behj, jaldi se

**Comment by kunalsinx** [comment]
MEIERINEHTVKFYMSYGDIEDRGFDREEIWYNRERSEELFWEVMDEVHEEEEFAVEGPLWIQVQALDKG
LEIIVTKAQLSKDGQKLELPIPEDKKQEPASEDLDALLDDFQKEEQAVNQEEKEQKLQFVLRFGDFEDVI
SLSKLNVNGSKTTLYSFENRYYLYVDFCNMTDEEVENQLSILLEYATESSISIHRLEEYGKLIISEHALE
TIKKHFAS
@ManashRaja
